server:
  port: 8080

spring:
  application:
    name: cherry-blog-application
  datasource:
    url: jdbc:mysql://localhost:3306/cherry_blog_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true